sudo : required

# travis will insatll docker
services: 
  - docker

# steps which need to occur    . uses current file to build
before_install:
  - docker build -t shane88/docker-react -f Dockerfile.dev .


script: 
  - docker run shane88/docker-react npm run test -- --coverage 


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-884107612257"
  bucket_path: "docker-react"

  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"

  secret_access_key:
    secure: "AWS_SECRET_KEY"